# Codecov configuration for RichPanel
# Standardizes PR comments, status checks, and coverage targets

coverage:
  status:
    # Project status: overall coverage change
    project:
      default:
        target: auto  # Don't fail if coverage is similar to base
        threshold: 5%  # Allow 5% drop before failing
        if_ci_failed: error

    # Patch status: new code must be reasonably tested
    patch:
      default:
        target: 50%  # Require at least 50% coverage on changed lines
        threshold: 10%  # Allow 10% variance
        if_ci_failed: error

comment:
  # Keep PR comments concise
  layout: "reach, diff, flags, files"
  behavior: default  # Update existing comment rather than creating new ones
  require_changes: true  # Only comment if coverage changed

flags:
  python:
    paths:
      - backend/
      - scripts/

# Ignore generated/vendored code
ignore:
  - "infra/cdk/cdk.out/**"
  - "**/*.md"
  - "**/test_*.py"  # Test files themselves don't need coverage
  - "**/__pycache__/**"

